services:
    sau.admin.configuration:
        class: Sau\Bundle\ConfigurationBundle\Admin\Configuration
        arguments:
            - ~
            - ~
            - Sau\Bundle\ConfigurationBundle\Controller\Admin\ConfigurationController
        tags:
            - { name: sonata.admin, manager_type: orm, group: Demo, label: Custom View }
